name: Check Mergability

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-merge-ability:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Comment
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            const commentAuthor = context.payload.comment.user.login;
            const prAuthor = context.payload.issue.user.login;

            let state = 'success';
            let description = 'The PR can be merged.';

            if (commentAuthor !== prAuthor) {
              state = 'failure';
              description = 'PR cannot be merged until the acknowledgment is present in the comment from the PR author.';
            } else if (!comment.includes('I acknowledge the instructions.')) {
              state = 'failure';
              description = 'PR cannot be merged until the acknowledgment is present in the comment.';
            }

            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: pr.data.head.sha,
              state: state,
              description: description,
              context: 'Check Mergability',
            });
