name: Check Mergability

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-merge-ability:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Comment
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const comment = context.payload.comment.body;
            const commentAuthor = context.payload.comment.user.login;
            const prAuthor = context.payload.issue.user.login;

            if (commentAuthor !== prAuthor) {
              core.setFailed('PR cannot be merged until the acknowledgment is present in the comment from the PR author.');
            } else if (!comment.includes('I acknowledge the instructions.')) {
              core.setFailed('PR cannot be merged until the acknowledgment is present in the comment.');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
