name: Check Mergability

on:
  issue_comment:
    types: [created, edited]

jobs:
  check-merge-ability:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Comment
        uses: actions/github-script@v7.0.1
        with:
          ithub-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body;
            const commentAuthor = context.payload.comment.user.login;
            const prAuthor = context.payload.issue.user.login;

            let conclusion = 'success';
            let output = {
              title: 'Check Mergability',
              summary: 'The PR can be merged.',
            };

            if (commentAuthor !== prAuthor) {
              conclusion = 'failure';
              output.summary = 'PR cannot be merged until the acknowledgment is present in the comment from the PR author.';
            } else if (!comment.includes('I acknowledge the instructions.')) {
              conclusion = 'failure';
              output.summary = 'PR cannot be merged until the acknowledgment is present in the comment.';
            }

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Check Mergability',
              head_sha: context.payload.pull_request.head.sha,
              status: 'completed',
              conclusion: conclusion,
              output: output,
            });
