name: PR Bot Workflow

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  comment-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prComment = `
            Thank you for opening this pull request! Please include the specific text message in your comment to proceed.

            Example: "I acknowledge the instructions."
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: prComment,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
