name: PR Bot Workflow

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  comment-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install yaml

      - name: Get PR author's email
        id: pr_author_email
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const user = await github.rest.users.getByUsername({
              username: pr.data.user.login
            });
            let email = user.data.email ;
            core.setOutput('email', email);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if author is whitelisted
        id: check
        run: node scripts/check-whitelist.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_AUTHOR_EMAIL: ${{ steps.pr_author_email.outputs.email }}

      - name: Comment on PR
        if: steps.check.outputs.is_whitelisted == 'false'
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prComment = `
            Thank you for opening this pull request! Please include the specific text message in your comment to proceed.

            Example: "I acknowledge the instructions."
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: prComment,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Report success
        if: steps.check.outputs.is_whitelisted == 'true'
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            (async ()=>{
            const pr = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              }).catch(err => {
                console.log('Error getting pull request:', err);
              });
            
            let result = await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: pr.data.head.sha,
                state: 'success',
                description: 'Author is already whitelisted',
                context: 'Check Mergability',
              }).catch(err => {
                console.log('Error creating commit status:', err);
              });
              console.log('Commit status created:', result);
              core.setOutput('state', result.data.state);
            })();